baseURL = "https://socialistlegacy.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Socialist Legacy"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"
summaryLength = 1

[taxonomies]
  tag = "tags"
  author = "authors"
  authors-sorted-alphabetically = "authors sorted alphabetically"
  source = "sources"
  source-date = "source dates"
  genre = "genres"
  year = "year"
  month = "month"
  book = "books"
  periodical = "periodicals"
  volume = "volume"
  issue = "issue"


[permalinks]
  year = "/date/:slug"
  month = "/date/:slug"
  periodicals = "/periodicals/:title"
  volume = "/periodicals/:title"
  issue = "/periodicals/:title"

[imaging]
  quality = 99

[params]
  description = "The Socialist Legacy"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "January 2, 2006"
  codePenUser = "someUser"
  mainSections = ["epigraphia", "ephemera"]


[menu]
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.nav]]
    name = "Ephemera"
    url = "/ephemera/"
    weight = 3
  [[menu.nav]]
    name = "Library"
    url = "/library/"
    weight = 4


  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.nav]]
    name = "Authors"
    url = "/authors/"
    weight = 4
